/**
 * Platform integrations: services we can connect to and sync data from.
 * Used by the Integrations/Extensions panel. Format: { id, name, description, category }.
 */
export const INTEGRATIONS_CATALOG = [
  // Productivity & docs
  { id: 'notion', name: 'Notion', description: 'Connect tasks, docs, and wikis. Sync pages and databases.', category: 'Productivity' },
  { id: 'confluence', name: 'Confluence', description: 'Atlassian wiki and knowledge base. Import spaces and pages.', category: 'Productivity' },
  { id: 'coda', name: 'Coda', description: 'Docs, tables, and apps. Sync doc content and tables.', category: 'Productivity' },
  { id: 'airtable', name: 'Airtable', description: 'Bases and views. Sync records and linked data.', category: 'Productivity' },
  { id: 'google-docs', name: 'Google Docs', description: 'Create and sync documents from Google Workspace.', category: 'Productivity' },
  { id: 'dropbox-paper', name: 'Dropbox Paper', description: 'Collaborative docs. Sync and open Paper docs.', category: 'Productivity' },
  { id: 'onenote', name: 'Microsoft OneNote', description: 'Notebooks and sections. Sync notes.', category: 'Productivity' },
  { id: 'obsidian', name: 'Obsidian', description: 'Local-first notes and vaults. Sync or link vaults.', category: 'Productivity' },
  { id: 'roam', name: 'Roam Research', description: 'Graph-based notes. Export or sync research.', category: 'Productivity' },
  { id: 'craft', name: 'Craft', description: 'Beautiful docs. Sync Craft documents.', category: 'Productivity' },
  { id: 'slite', name: 'Slite', description: 'Team knowledge base. Sync channels and docs.', category: 'Productivity' },
  { id: 'gitbook', name: 'GitBook', description: 'Documentation and guides. Sync spaces.', category: 'Productivity' },
  { id: 'readme', name: 'ReadMe', description: 'API and product docs. Sync documentation.', category: 'Productivity' },
  // Dev & code
  { id: 'github', name: 'GitHub', description: 'Repos, issues, PRs. Sync issues and integrate with repositories.', category: 'Dev' },
  { id: 'gitlab', name: 'GitLab', description: 'Merge requests, issues, CI. Connect to GitLab projects.', category: 'Dev' },
  { id: 'bitbucket', name: 'Bitbucket', description: 'Atlassian Git. Repos, PRs, and pipelines.', category: 'Dev' },
  { id: 'azure-devops', name: 'Azure DevOps', description: 'Boards, repos, pipelines. Sync work items and builds.', category: 'Dev' },
  { id: 'gitea', name: 'Gitea', description: 'Self-hosted Git. Issues and PRs.', category: 'Dev' },
  { id: 'sourcehut', name: 'Sourcehut', description: 'Git hosting and CI. Projects and builds.', category: 'Dev' },
  { id: 'gerrit', name: 'Gerrit', description: 'Code review. Connect to Gerrit changes.', category: 'Dev' },
  { id: 'launchpad', name: 'Launchpad', description: 'Bugs and code. Ubuntu project integration.', category: 'Dev' },
  { id: 'phabricator', name: 'Phabricator', description: 'Code review and tasks. Differential and Maniphest.', category: 'Dev' },
  { id: 'circleci', name: 'CircleCI', description: 'CI/CD pipelines. View builds and artifacts.', category: 'Dev' },
  { id: 'travis-ci', name: 'Travis CI', description: 'Build status and logs. Connect to Travis.', category: 'Dev' },
  { id: 'jenkins', name: 'Jenkins', description: 'Builds and jobs. Monitor Jenkins pipelines.', category: 'Dev' },
  { id: 'vercel', name: 'Vercel', description: 'Deployments and previews. Link Vercel projects.', category: 'Dev' },
  { id: 'netlify', name: 'Netlify', description: 'Sites and deploys. Connect Netlify sites.', category: 'Dev' },
  { id: 'railway', name: 'Railway', description: 'Deploy apps and services. Link Railway projects.', category: 'Dev' },
  { id: 'render', name: 'Render', description: 'Hosting and backends. Sync Render services.', category: 'Dev' },
  { id: 'fly-io', name: 'Fly.io', description: 'Edge apps. Connect Fly apps.', category: 'Dev' },
  { id: 'sentry', name: 'Sentry', description: 'Errors and performance. View issues and releases.', category: 'Dev' },
  { id: 'datadog', name: 'Datadog', description: 'Monitoring and APM. Dashboards and alerts.', category: 'Dev' },
  { id: 'new-relic', name: 'New Relic', description: 'Observability. Apps and metrics.', category: 'Dev' },
  { id: 'grafana', name: 'Grafana', description: 'Dashboards and alerts. Connect Grafana instances.', category: 'Dev' },
  { id: 'pagerduty', name: 'PagerDuty', description: 'Incidents and on-call. Sync incidents.', category: 'Dev' },
  { id: 'opsgenie', name: 'Opsgenie', description: 'Alerting and on-call. Connect Opsgenie.', category: 'Dev' },
  // Project management
  { id: 'jira', name: 'Jira', description: 'Atlassian issues and sprints. Sync boards and backlogs.', category: 'Project Management' },
  { id: 'linear', name: 'Linear', description: 'Issues and cycles. Sync Linear workspace.', category: 'Project Management' },
  { id: 'asana', name: 'Asana', description: 'Tasks and projects. Sync workspaces and tasks.', category: 'Project Management' },
  { id: 'trello', name: 'Trello', description: 'Boards and cards. Sync boards and lists.', category: 'Project Management' },
  { id: 'monday', name: 'Monday.com', description: 'Work OS. Sync boards and items.', category: 'Project Management' },
  { id: 'clickup', name: 'ClickUp', description: 'Tasks, docs, goals. Connect ClickUp workspace.', category: 'Project Management' },
  { id: 'basecamp', name: 'Basecamp', description: 'Projects and campfires. Sync Basecamp 3.', category: 'Project Management' },
  { id: 'shortcut', name: 'Shortcut', description: 'Stories and iterations. Connect Shortcut.', category: 'Project Management' },
  { id: 'pivotal-tracker', name: 'Pivotal Tracker', description: 'Stories and velocity. Sync Pivotal projects.', category: 'Project Management' },
  { id: 'wrike', name: 'Wrike', description: 'Projects and tasks. Sync Wrike space.', category: 'Project Management' },
  { id: 'smartsheet', name: 'Smartsheet', description: 'Sheets and automation. Connect Smartsheet.', category: 'Project Management' },
  { id: 'teamwork', name: 'Teamwork', description: 'Projects and time. Sync Teamwork.', category: 'Project Management' },
  { id: 'todoist', name: 'Todoist', description: 'Tasks and projects. Sync Todoist.', category: 'Project Management' },
  { id: 'things', name: 'Things', description: 'Tasks and areas. Connect Things (if API available).', category: 'Project Management' },
  { id: 'ticktick', name: 'TickTick', description: 'Tasks and calendar. Sync TickTick.', category: 'Project Management' },
  { id: 'any-do', name: 'Any.do', description: 'Tasks and lists. Connect Any.do.', category: 'Project Management' },
  // Communication
  { id: 'slack', name: 'Slack', description: 'Channels and messages. Notifications and search.', category: 'Communication' },
  { id: 'discord', name: 'Discord', description: 'Servers and channels. Connect Discord.', category: 'Communication' },
  { id: 'microsoft-teams', name: 'Microsoft Teams', description: 'Chat and channels. Connect Teams.', category: 'Communication' },
  { id: 'zoom', name: 'Zoom', description: 'Meetings and webinars. Schedule and join.', category: 'Communication' },
  { id: 'google-meet', name: 'Google Meet', description: 'Video meetings. Start and join.', category: 'Communication' },
  { id: 'whereby', name: 'Whereby', description: 'Embedded video. Connect Whereby.', category: 'Communication' },
  { id: 'loom', name: 'Loom', description: 'Async video. View and create Looms.', category: 'Communication' },
  { id: 'twist', name: 'Twist', description: 'Async team chat. Sync Twist threads.', category: 'Communication' },
  { id: 'zulip', name: 'Zulip', description: 'Threaded chat. Connect Zulip.', category: 'Communication' },
  { id: 'mattermost', name: 'Mattermost', description: 'Self-hosted Slack alternative. Connect Mattermost.', category: 'Communication' },
  { id: 'rocket-chat', name: 'Rocket.Chat', description: 'Open-source chat. Connect Rocket.Chat.', category: 'Communication' },
  // Design
  { id: 'figma', name: 'Figma', description: 'Design files and prototypes. Embed and link frames.', category: 'Design' },
  { id: 'miro', name: 'Miro', description: 'Whiteboards and workshops. Sync boards.', category: 'Design' },
  { id: 'whimsical', name: 'Whimsical', description: 'Wireframes and flowcharts. Connect Whimsical.', category: 'Design' },
  { id: 'sketch', name: 'Sketch', description: 'Design files. Connect Sketch (cloud).', category: 'Design' },
  { id: 'invision', name: 'InVision', description: 'Prototypes and specs. Connect InVision.', category: 'Design' },
  { id: 'abstract', name: 'Abstract', description: 'Design version control. Connect Abstract.', category: 'Design' },
  { id: 'framer', name: 'Framer', description: 'Design and code. Connect Framer.', category: 'Design' },
  { id: 'canva', name: 'Canva', description: 'Templates and design. Connect Canva.', category: 'Design' },
  // CRM & sales
  { id: 'salesforce', name: 'Salesforce', description: 'CRM and sales. Sync leads and opportunities.', category: 'CRM & Sales' },
  { id: 'hubspot', name: 'HubSpot', description: 'Marketing and CRM. Contacts and deals.', category: 'CRM & Sales' },
  { id: 'pipedrive', name: 'Pipedrive', description: 'Sales pipeline. Sync deals.', category: 'CRM & Sales' },
  { id: 'zoho-crm', name: 'Zoho CRM', description: 'CRM and pipeline. Connect Zoho.', category: 'CRM & Sales' },
  { id: 'close', name: 'Close', description: 'Sales communication. Connect Close.', category: 'CRM & Sales' },
  // Support
  { id: 'zendesk', name: 'Zendesk', description: 'Tickets and help center. Sync support tickets.', category: 'Support' },
  { id: 'intercom', name: 'Intercom', description: 'Conversations and articles. Connect Intercom.', category: 'Support' },
  { id: 'freshdesk', name: 'Freshdesk', description: 'Support tickets. Sync Freshdesk.', category: 'Support' },
  { id: 'freshservice', name: 'Freshservice', description: 'ITSM and tickets. Connect Freshservice.', category: 'Support' },
  { id: 'help-scout', name: 'Help Scout', description: 'Customer conversations. Connect Help Scout.', category: 'Support' },
  { id: 'crisp', name: 'Crisp', description: 'Chat and inbox. Connect Crisp.', category: 'Support' },
  { id: 'front', name: 'Front', description: 'Shared inbox. Sync Front.', category: 'Support' },
  // Calendar & scheduling
  { id: 'google-calendar', name: 'Google Calendar', description: 'Events and availability. Sync calendars.', category: 'Calendar' },
  { id: 'outlook-calendar', name: 'Outlook Calendar', description: 'Microsoft 365 calendar. Sync events.', category: 'Calendar' },
  { id: 'calendly', name: 'Calendly', description: 'Scheduling. Connect Calendly.', category: 'Calendar' },
  { id: 'cal-com', name: 'Cal.com', description: 'Open-source scheduling. Connect Cal.com.', category: 'Calendar' },
  { id: 'doodle', name: 'Doodle', description: 'Polls and scheduling. Connect Doodle.', category: 'Calendar' },
  // Storage & files
  { id: 'google-drive', name: 'Google Drive', description: 'Files and folders. Sync and open files.', category: 'Storage' },
  { id: 'onedrive', name: 'OneDrive', description: 'Microsoft cloud storage. Sync files.', category: 'Storage' },
  { id: 'dropbox', name: 'Dropbox', description: 'Files and sharing. Sync Dropbox.', category: 'Storage' },
  { id: 'box', name: 'Box', description: 'Enterprise file share. Connect Box.', category: 'Storage' },
  { id: 'icloud', name: 'iCloud Drive', description: 'Apple cloud storage. Sync iCloud.', category: 'Storage' },
  // Email
  { id: 'gmail', name: 'Gmail', description: 'Read and send. Connect Gmail.', category: 'Email' },
  { id: 'outlook', name: 'Outlook', description: 'Microsoft 365 email. Connect Outlook.', category: 'Email' },
  { id: 'superhuman', name: 'Superhuman', description: 'Fast email. Connect Superhuman.', category: 'Email' },
  // Analytics & data
  { id: 'google-analytics', name: 'Google Analytics', description: 'Web analytics. Dashboards and properties.', category: 'Analytics' },
  { id: 'mixpanel', name: 'Mixpanel', description: 'Product analytics. Events and funnels.', category: 'Analytics' },
  { id: 'amplitude', name: 'Amplitude', description: 'Product and behavior. Connect Amplitude.', category: 'Analytics' },
  { id: 'segment', name: 'Segment', description: 'CDP and pipelines. Connect Segment.', category: 'Analytics' },
  { id: 'heap', name: 'Heap', description: 'Autocapture analytics. Connect Heap.', category: 'Analytics' },
  { id: 'posthog', name: 'PostHog', description: 'Product analytics. Self-hosted or cloud.', category: 'Analytics' },
  { id: 'fullstory', name: 'FullStory', description: 'Session replay. Connect FullStory.', category: 'Analytics' },
  { id: 'hotjar', name: 'Hotjar', description: 'Heatmaps and feedback. Connect Hotjar.', category: 'Analytics' },
  // AI & ML (platforms)
  { id: 'helox', name: 'Helox Pipelines', description: 'Run training and RAG pipelines from the IDE with live output.', category: 'AI & ML' },
  { id: 'cyrex', name: 'Cyrex AI', description: 'Agent Playground, RAG, Workflows, task classification.', category: 'AI & ML' },
  { id: 'openai', name: 'OpenAI', description: 'GPT and API. Use OpenAI in the app.', category: 'AI & ML' },
  { id: 'anthropic', name: 'Anthropic', description: 'Claude API. Connect Anthropic.', category: 'AI & ML' },
  { id: 'replicate', name: 'Replicate', description: 'Run ML models. Connect Replicate.', category: 'AI & ML' },
  { id: 'huggingface', name: 'Hugging Face', description: 'Models and datasets. Connect Hugging Face.', category: 'AI & ML' },
  { id: 'weights-biases', name: 'Weights & Biases', description: 'ML experiment tracking. Sync runs.', category: 'AI & ML' },
  { id: 'mlflow', name: 'MLflow', description: 'ML lifecycle. Connect MLflow.', category: 'AI & ML' },
  { id: 'comet', name: 'Comet', description: 'ML experiment tracking. Connect Comet.', category: 'AI & ML' },
  // Other
  { id: 'stripe', name: 'Stripe', description: 'Payments and billing. Connect Stripe.', category: 'Payments' },
  { id: 'twilio', name: 'Twilio', description: 'SMS and voice. Connect Twilio.', category: 'Communication' },
  { id: 'sendgrid', name: 'SendGrid', description: 'Email delivery. Connect SendGrid.', category: 'Email' },
  { id: 'mailchimp', name: 'Mailchimp', description: 'Email marketing. Connect Mailchimp.', category: 'Marketing' },
  { id: 'typeform', name: 'Typeform', description: 'Forms and surveys. Connect Typeform.', category: 'Productivity' },
  { id: 'tally', name: 'Tally', description: 'Forms. Connect Tally.', category: 'Productivity' },
  { id: 'n8n', name: 'n8n', description: 'Workflow automation. Connect n8n.', category: 'Automation' },
  { id: 'zapier', name: 'Zapier', description: 'Automations. Connect Zapier.', category: 'Automation' },
  { id: 'make', name: 'Make (Integromat)', description: 'Visual automation. Connect Make.', category: 'Automation' },
  { id: 'ifttt', name: 'IFTTT', description: 'Applets. Connect IFTTT.', category: 'Automation' },
];
